name: Daily Activity

on: 
  schedule:
    - cron: "0 0 * * *"

jobs:

  update-readme:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update README
      run: |
        date >> README.md
        
    - name: Setup Git
      run: |
        git config user.name "ramincsy"
        git config user.email "ramincsy2@gmail.com"
        
    - name: Commit changes
      run: |
        git add .
        git commit -m "Daily update"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
