name: Repeat Activity

on:
  schedule:
    - cron: '*/1 * * * *' # هر ۱ دقیقه یک بار

jobs:
  repeat_activity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create New Code File
      run: |
        echo "Your Code Here - $(date)" >> new_code_$(date "+%Y%m%d%H%M%S").js

    - name: Commit and Push Changes
      run: |
        git config --global user.email "ramincsy2@gmail.com"
        git config --global user.name "ramincsy"
        git add .
        git commit -m "Add new code - $(date)"
        git push
