name: Repeat Activity

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:
    
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
      
    - name: Setup GitHub Credentials  
      uses: github/gh-action@v4
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Create File
      run: |
        echo "Your Code" >> file.txt
    
    - uses: EndBug/add-and-commit@v7
      with:
        message: "Add file"
        add: "."
        
    - uses: ad-m/github-push-action@master
      with: 
        token: ${{ secrets.PERSONAL_TOKEN }}
